SELECT * FROM funcionario

SELECT FUNCIONARIO.FUNCIONARIONOME,
	   FUNCIONARIO.FUNCIONARIOSALARIO,
	   GERENTES.FUNCIONARIONOME AS GERENTE
FROM FUNCIONARIO 
	   LEFT OUTER JOIN FUNCIONARIO GERENTES
	   ON FUNCIONARIO.FUNCIONARIOCODIGOGERENTE =
	   GERENTES.FUNCIONARIOID

SELECT * FROM GradeSalario

SELECT FUNCIONARIO.FUNCIONARIONOME,
       FUNCIONARIO.FUNCIONARIOSALARIO,
	   GRADESALARIO.GRADENIVEL

FROM FUNCIONARIO
	 LEFT OUTER JOIN GRADESALARIO
	 ON FUNCIONARIO.FUNCIONARIOSALARIO
	 BETWEEN GRADESALARIO.SALARIOMINIMO AND
			 GRADESALARIO.SALARIOMAXIMO

/* VIEW -> É UM OBJETO DO BANCO QUE ARMAZENA UM SQL, QUANDO 
		VOCÊ FAZ UM SELECT NA VIEW ELA EXECUTA O SQL */

DROP VIEW VFUNCIONARIOS;

CREATE VIEW VFUNCIONARIOS
AS
SELECT FUNCIONARIO.FUNCIONARIONOME,
	   CARGO.CARGODESCRICAO,
	   DEPARTAMENTO.DEPARTAMENTONOME,
	   LOCALIDADE.LOCALIDADENOME,
	   PAIS.PAISNOME
FROM FUNCIONARIO
	 LEFT OUTER JOIN CARGO
	 ON FUNCIONARIO.CARGOID = CARGO.CARGOID
	 LEFT OUTER JOIN DEPARTAMENTO
	 ON FUNCIONARIO.DEPARTAMENTOID = DEPARTAMENTO.DEPARTAMENTOID
	 LEFT OUTER JOIN LOCALIDADE
	 ON DEPARTAMENTO.LOCALIDADEID = LOCALIDADE.LOCALIDADEID
	 LEFT OUTER JOIN PAIS
	 ON LOCALIDADE.LOCALIDADEPAIS = PAIS.PAISID

SELECT * FROM VFUNCIONARIOS

/* PROCEDURE -> OBJETO QUE ARMAZENA UM SQL E EXECUTA ELA QUANDO É CHAMADA
A PROCEDURE PODE REALIZAR OPERAÇÕES DE INSERT, UPDATE E DELETE */

SELECT * FROM CARGO

EXEC LISTA_FUNCIONARIOS 2

DROP PROCEDURE LISTA_FUNCIONARIOS

CREATE PROCEDURE LISTA_FUNCIONARIOS
@CARGOID INT
AS
SELECT FUNCIONARIO.FUNCIONARIONOME,
	   CARGO.CARGODESCRICAO,
	   DEPARTAMENTO.DEPARTAMENTONOME,
	   LOCALIDADE.LOCALIDADENOME,
	   PAIS.PAISNOME
FROM FUNCIONARIO
	 LEFT OUTER JOIN CARGO
	 ON FUNCIONARIO.CARGOID = CARGO.CARGOID
	 LEFT OUTER JOIN DEPARTAMENTO
	 ON FUNCIONARIO.DEPARTAMENTOID = DEPARTAMENTO.DEPARTAMENTOID
	 LEFT OUTER JOIN LOCALIDADE
	 ON DEPARTAMENTO.LOCALIDADEID = LOCALIDADE.LOCALIDADEID
	 LEFT OUTER JOIN PAIS
	 ON LOCALIDADE.LOCALIDADEPAIS = PAIS.PAISID
WHERE CARGO.CARGOID = @CARGOID

/* PROCEDURE COM COMANDOS DML */

CREATE PROCEDURE INSERE_PAIS
@NOME VARCHAR(30),
@DDI VARCHAR(5)
AS

INSERT INTO PAIS (PAISNOME, PAISDDI)
		   VALUES(@NOME,@DDI)
		   
---EXECUTAR
SELECT * FROM PAIS
INSERE_PAIS 'URUGUAI','+56'