CREATE TABLE LOG_SALARIO
(
FuncionarioId INT,
SalarioAntigo DECIMAL(12,2),
SalarioNovo DECIMAL(12,2),
DataAlteracao DATETIME DEFAULT GETDATE()
)

/* TRIGGER - OBJETO DE BANCO DE DADOS QUE É ACIONADO QUANDO TEM ALGUM
			 COMO (Insert, Update, Delte) EM ALGUMA TABELA */

